"""Updated models to remove SingleTransactionLog

Revision ID: 7dd9af6cfed9
Revises: 
Create Date: 2025-04-21 14:55:27.179485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd9af6cfed9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_transaction_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_transaction_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('step', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('nameOrig', sa.VARCHAR(length=100), nullable=True),
    sa.Column('oldbalanceOrg', sa.FLOAT(), nullable=True),
    sa.Column('newbalanceOrig', sa.FLOAT(), nullable=True),
    sa.Column('nameDest', sa.VARCHAR(length=100), nullable=True),
    sa.Column('oldbalanceDest', sa.FLOAT(), nullable=True),
    sa.Column('newbalanceDest', sa.FLOAT(), nullable=True),
    sa.Column('prediction', sa.VARCHAR(length=10), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
